//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLQ_MBE_BattleSimulation.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JLQ_MBE_BattleSimulation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Display=爱
        ///maxHp=130
        ///attack=97
        ///defence=80
        ///hitRate=80
        ///dodgeRate=54
        ///closeAmendment=0.9
        ///interval=30
        ///moveAbility=3
        ///attackRange=3
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Alice {
            get {
                return ResourceManager.GetString("Alice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=
        ///maxHp=
        ///attack=
        ///defence=
        ///hitRate=
        ///dodgeRate=
        ///closeAmendment=
        ///interval=
        ///moveAbility=
        ///attackRange= 的本地化字符串。
        /// </summary>
        internal static string CharacterTemplate {
            get {
                return ResourceManager.GetString("CharacterTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=橙
        ///maxHp=120
        ///attack=95
        ///defence=85
        ///hitRate=75
        ///dodgeRate=65
        ///closeAmendment=1.2
        ///interval=26
        ///moveAbility=4
        ///attackRange=2
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Chen {
            get {
                return ResourceManager.GetString("Chen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=⑨
        ///maxHp=140
        ///attack=90
        ///defence=83
        ///hitRate=80
        ///dodgeRate=57
        ///closeAmendment=1.1
        ///interval=30
        ///moveAbility=3
        ///attackRange=1
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Cirno {
            get {
                return ResourceManager.GetString("Cirno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=大酱
        ///maxHp=75
        ///attack=75
        ///defence=60
        ///hitRate=75
        ///dodgeRate=62
        ///closeAmendment=0.5
        ///interval=29
        ///moveAbility=4
        ///attackRange=2
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Daiyousei {
            get {
                return ResourceManager.GetString("Daiyousei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=永
        ///maxHp=185
        ///attack=105
        ///defence=100
        ///hitRate=90
        ///dodgeRate=53
        ///closeAmendment=0.7
        ///interval=33
        ///moveAbility=3
        ///attackRange=4
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Eirin {
            get {
                return ResourceManager.GetString("Eirin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=芙
        ///maxHp=150
        ///attack=130
        ///defence=90
        ///hitRate=80
        ///dodgeRate=60
        ///closeAmendment=1.2
        ///interval=39
        ///moveAbility=3
        ///attackRange=1
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Flandre {
            get {
                return ResourceManager.GetString("Flandre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=毛
        ///maxHp=120
        ///attack=100
        ///defence=80
        ///hitRate=80
        ///dodgeRate=60
        ///closeAmendment=1
        ///interval=30
        ///moveAbility=3
        ///attackRange=3
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Gedama {
            get {
                return ResourceManager.GetString("Gedama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=辉
        ///maxHp=165
        ///attack=115
        ///defence=85
        ///hitRate=75
        ///dodgeRate=46
        ///closeAmendment=0.5
        ///interval=38
        ///moveAbility=2
        ///attackRange=4
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Kaguya {
            get {
                return ResourceManager.GetString("Kaguya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=慧
        ///maxHp=155
        ///attack=96
        ///defence=95
        ///hitRate=75
        ///dodgeRate=50
        ///closeAmendment=1.1
        ///interval=37
        ///moveAbility=3
        ///attackRange=2
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Keine {
            get {
                return ResourceManager.GetString("Keine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=小
        ///maxHp=100
        ///attack=80
        ///defence=80
        ///hitRate=80
        ///dodgeRate=55
        ///closeAmendment=1
        ///interval=28
        ///moveAbility=4
        ///attackRange=3
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Koakuma {
            get {
                return ResourceManager.GetString("Koakuma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=蕾拉
        ///maxHp=65
        ///attack=50
        ///defence=70
        ///hitRate=65
        ///dodgeRate=50
        ///closeAmendment=0.2
        ///interval=25
        ///moveAbility=3
        ///attackRange=3
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Leira {
            get {
                return ResourceManager.GetString("Leira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=蕾蒂
        ///maxHp=130
        ///attack=90
        ///defence=80
        ///hitRate=70
        ///dodgeRate=55
        ///closeAmendment=0.9
        ///interval=27
        ///moveAbility=3
        ///attackRange=3
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Letty {
            get {
                return ResourceManager.GetString("Letty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=莉
        ///maxHp=65
        ///attack=75
        ///defence=60
        ///hitRate=55
        ///dodgeRate=55
        ///closeAmendment=0.5
        ///interval=29
        ///moveAbility=3
        ///attackRange=3
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string LilyWhite {
            get {
                return ResourceManager.GetString("LilyWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=弦
        ///maxHp=105
        ///attack=85
        ///defence=75
        ///hitRate=75
        ///dodgeRate=55
        ///closeAmendment=0.7
        ///interval=30
        ///moveAbility=3
        ///attackRange=3
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Lunasa {
            get {
                return ResourceManager.GetString("Lunasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=键
        ///maxHp=100
        ///attack=85
        ///defence=75
        ///hitRate=70
        ///dodgeRate=58
        ///closeAmendment=0.7
        ///interval=26
        ///moveAbility=3
        ///attackRange=3
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Lyrica {
            get {
                return ResourceManager.GetString("Lyrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=魔
        ///maxHp=115
        ///attack=115
        ///defence=85
        ///hitRate=80
        ///dodgeRate=60
        ///closeAmendment=1
        ///interval=28
        ///moveAbility=4
        ///attackRange=5
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Marisa {
            get {
                return ResourceManager.GetString("Marisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=红
        ///maxHp=140
        ///attack=95
        ///defence=97
        ///hitRate=80
        ///dodgeRate=57
        ///closeAmendment=1.3
        ///interval=30
        ///moveAbility=3
        ///attackRange=1
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Meirin {
            get {
                return ResourceManager.GetString("Meirin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=管
        ///maxHp=110
        ///attack=85
        ///defence=80
        ///hitRate=70
        ///dodgeRate=55
        ///closeAmendment=0.7
        ///interval=29
        ///moveAbility=3
        ///attackRange=3
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Merlin {
            get {
                return ResourceManager.GetString("Merlin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=妹
        ///maxHp=205
        ///attack=110
        ///defence=115
        ///hitRate=80
        ///dodgeRate=55
        ///closeAmendment=1.3
        ///interval=34
        ///moveAbility=3
        ///attackRange=2
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Mokou {
            get {
                return ResourceManager.GetString("Mokou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=雀
        ///maxHp=120
        ///attack=90
        ///defence=65
        ///hitRate=80
        ///dodgeRate=65
        ///closeAmendment=1
        ///interval=27
        ///moveAbility=4
        ///attackRange=3
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Mystia {
            get {
                return ResourceManager.GetString("Mystia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=帕
        ///maxHp=100
        ///attack=120
        ///defence=80
        ///hitRate=85
        ///dodgeRate=40
        ///closeAmendment=0.1
        ///interval=40
        ///moveAbility=2
        ///attackRange=4
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Patchouli {
            get {
                return ResourceManager.GetString("Patchouli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=蓝
        ///maxHp=175
        ///attack=105
        ///defence=110
        ///hitRate=80
        ///dodgeRate=50
        ///closeAmendment=0.8
        ///interval=33
        ///moveAbility=4
        ///attackRange=3
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Ran {
            get {
                return ResourceManager.GetString("Ran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=蕾
        ///maxHp=140
        ///attack=105
        ///defence=80
        ///hitRate=100
        ///dodgeRate=65
        ///closeAmendment=1.2
        ///interval=31
        ///moveAbility=3
        ///attackRange=1
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Reimiria {
            get {
                return ResourceManager.GetString("Reimiria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=梦
        ///maxHp=125
        ///attack=105
        ///defence=90
        ///hitRate=90
        ///dodgeRate=67
        ///closeAmendment=1
        ///interval=14
        ///moveAbility=3
        ///attackRange=4
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Reimu {
            get {
                return ResourceManager.GetString("Reimu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=兔
        ///maxHp=130
        ///attack=98
        ///defence=80
        ///hitRate=80
        ///dodgeRate=60
        ///closeAmendment=0.8
        ///interval=33
        ///moveAbility=3
        ///attackRange=4
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Reisen {
            get {
                return ResourceManager.GetString("Reisen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=麟
        ///maxHp=140
        ///attack=100
        ///defence=95
        ///hitRate=80
        ///dodgeRate=65
        ///closeAmendment=1.2
        ///interval=31
        ///moveAbility=3
        ///attackRange=3
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Rin {
            get {
                return ResourceManager.GetString("Rin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=⑩
        ///maxHp=100
        ///attack=85
        ///defence=80
        ///hitRate=80
        ///dodgeRate=60
        ///closeAmendment=1.2
        ///interval=28
        ///moveAbility=3
        ///attackRange=1
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Rumia {
            get {
                return ResourceManager.GetString("Rumia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=16
        ///maxHp=120
        ///attack=101
        ///defence=82
        ///hitRate=80
        ///dodgeRate=70
        ///closeAmendment=1.2
        ///interval=25
        ///moveAbility=4
        ///attackRange=3
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Sakuya {
            get {
                return ResourceManager.GetString("Sakuya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=萃
        ///maxHp=220
        ///attack=125
        ///defence=130
        ///hitRate=65
        ///dodgeRate=40
        ///closeAmendment=1.5
        ///interval=37
        ///moveAbility=3
        ///attackRange=1
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Suika {
            get {
                return ResourceManager.GetString("Suika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=帝
        ///maxHp=125
        ///attack=85
        ///defence=75
        ///hitRate=90
        ///dodgeRate=65
        ///closeAmendment=1
        ///interval=27
        ///moveAbility=4
        ///attackRange=3
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Tewi {
            get {
                return ResourceManager.GetString("Tewi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=虫
        ///maxHp=140
        ///attack=85
        ///defence=65
        ///hitRate=60
        ///dodgeRate=50
        ///closeAmendment=1.1
        ///interval=29
        ///moveAbility=3
        ///attackRange=3
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Wriggle {
            get {
                return ResourceManager.GetString("Wriggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=妖梦
        ///maxHp=140
        ///attack=100
        ///defence=70
        ///hitRate=80
        ///dodgeRate=65
        ///closeAmendment=1.4
        ///interval=23
        ///moveAbility=4
        ///attackRange=2
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Youmu {
            get {
                return ResourceManager.GetString("Youmu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=紫
        ///maxHp=185
        ///attack=110
        ///defence=100
        ///hitRate=75
        ///dodgeRate=70
        ///closeAmendment=0.8
        ///interval=37
        ///moveAbility=5
        ///attackRange=3
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Yukari {
            get {
                return ResourceManager.GetString("Yukari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display=幽
        ///maxHp=190
        ///attack=110
        ///defence=105
        ///hitRate=65
        ///dodgeRate=50
        ///closeAmendment=1
        ///interval=40
        ///moveAbility=2
        ///attackRange=4
        ///scName[0]=飞翔于天空中不可思议的巫女
        ///scName[1]=灵符「梦想封印」
        ///scName[2]=神技「八方鬼缚阵」
        ///scName[3]=博丽秘技「梦想天生」
        ///scDisc[0]=你可以穿过敌方单位。
        ///scDisc[1]=梦想封印
        ///scDisc[2]=八方鬼缚阵
        ///scDisc[3]=梦想天生
        /// 的本地化字符串。
        /// </summary>
        internal static string Yuyuko {
            get {
                return ResourceManager.GetString("Yuyuko", resourceCulture);
            }
        }
    }
}
